// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlcHXtzbJEm2ui09tC5e2NvAQgvvBE6so',
    appId: '1:621147548567:web:2d29293702d9d72f9f32d2',
    messagingSenderId: '621147548567',
    projectId: 'ebook-9675c',
    authDomain: 'ebook-9675c.firebaseapp.com',
    storageBucket: 'ebook-9675c.appspot.com',
    measurementId: 'G-JH2YY833SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKQ0rcJjs0Zt2A8DGa3gEmXc5pWXU1YDA',
    appId: '1:621147548567:android:9c68e1ca65c04f3f9f32d2',
    messagingSenderId: '621147548567',
    projectId: 'ebook-9675c',
    storageBucket: 'ebook-9675c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxnEqqrJrwoYas7MidLJpzZxBrro9WUkw',
    appId: '1:621147548567:ios:da7845d942ac2a259f32d2',
    messagingSenderId: '621147548567',
    projectId: 'ebook-9675c',
    storageBucket: 'ebook-9675c.appspot.com',
    iosBundleId: 'com.ebook.nayon.coders.app',
  );
}
